sudo: required
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

language: node_js
cache: yarn
script:
  - yarn --version
  - yarn check --integrity
  - yarn setup
#  - yarn lint
#  - yarn test
#  - yarn test:routes
  - yarn test:a11y
#  - yarn test:coverage-unit
#after_success:
#  - yarn test:codacy-upload
#  - yarn test:codecov-upload
