version: '2.1'

services:
    integration-tests:
      image: docker.artifactory.reform.hmcts.net/cmc/integration-tests:${INTEGRATION_TESTS_VERSION:-latest}
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - CITIZEN_APP_URL=${TEST_URL}
          #        - CITIZEN_APP_URL=https://www-test.moneyclaim.reform.hmcts.net
          # - CITIZEN_APP_URL=https://www.moneyclaim.reform.hmcts.net
        - IDAM_URL=http://betaDevBccidamAppLB.reform.hmcts.net
        - CLAIM_STORE_URL=http://docker.for.mac.localhost:4300
        - SMOKE_TEST_USERNAME=civilmoneyclaims+smoketest@gmail.com
        - SMOKE_TEST_PASSWORD=Password12
        - HEALTHCHECK_CITIZEN=true
      volumes:
        - ./output:/usr/src/app/output
    remote-webdriver:
      image: docker.artifactory.reform.hmcts.net/selenium/standalone-chrome:3.8.1

