version: '2.1'

services:
    citizen-integration-tests:
      image: hmctspublic.azurecr.io/cmc/citizen-integration-tests:${CITIZEN_INTEGRATION_TESTS_VERSION:-latest}
      command: test:integration
      environment:
        - WEB_DRIVER_HOST=remote-webdriver
        - CITIZEN_APP_URL=${TEST_URL}
        - CLAIM_STORE_URL
        - IDAM_URL
        - OAUTH_CLIENT_SECRET
        - SMOKE_TEST_CITIZEN_USERNAME
        - SMOKE_TEST_USER_PASSWORD
        - HEALTHCHECK_CITIZEN=true
        - FEATURE_ADMISSIONS
        - FEATURE_MEDIATION
        - FEATURE_DIRECTIONS_QUESTIONNAIRE
        - FEATURE_TESTING_SUPPORT
        - FEATURE_INVERSION_OF_CONTROL
        - FEATURE_PCQ
      volumes:
        - ./functional-output:/usr/src/app/output
    remote-webdriver:
      image: selenium/standalone-chrome:3.8.1
