dependencies:
  - name: nodejs
    version: ~1.8.0
    repository: '@hmctspublic'

  - name: idam-pr
    version: ~2.1.0
    repository: '@hmctspublic'
    tags:
      - idam-pr
    condition: idam-pr.enabled

  - name: rpe-feature-toggle-api
    version: ~3.1.0
    repository: '@hmctspublic'
    tags:
      - rpe-feature-toggle-api-pod

  - name: cmc-claim-store
    version: ~2.0.0
    repository: '@hmctspublic'
    tags:
      - cmc-claim-store-pod

  - name: postgresql
    version: ~2.6.5
    repository: '@stable'
    tags:
      - cmc-frontend-postgresql-pod

  - name: ccd
    version: ~3.3.1
    repository: '@hmctspublic'
    tags:
      - frontend-ccd-stack
